### PR TITLE
Adding checked class

### PR DESCRIPTION
**Pull request by Tomino2112**
This is my solution for #24

### CODE REVIEW

**Comment by sebastianha** [comment]
Hi,

The checkbox automatically get the class "checked" when it is checked, perhaps this is the easiest solution for you?

Regards, Sebastian

**Comment by Tomino2112** [comment]
@sebastianha Hi, the thing is that I want to change the button style from default to success. 

So: `<checkbox ng-model="page.is_active" class="btn pull-right" checked-class="btn-success"></checkbox>` 

If I would use "checked" class I would have to copy all styles for `btn-success` which is not the best way to do it

**Comment by Tomino2112** [comment]
@sebastianha  Actually inspecting the code, there is no `checked` class added to the button. Only class change is on span element inside of it that gets `glyphicon-ok` class when checked. 

Which could be also improved, people might want to display different icon/image on checked

**Comment by sebastianha** [comment]
When I am using the test-html file the checked class is added to the button element.

But you are right, it is complicated if you just want to add the btn-success style when it is checked.

I will think about it. I would add an unchecked-class attribute, too, so you can also style unchecked checkboxes.

**Comment by sebastianha** [comment]
Take a look at https://github.com/sebastianha/angular-bootstrap-checkbox/tree/checked-unchecked

what do you think?

By the way: I had to increase the minimum angular version to 1.4.0 as ng-class behaves different before.

**Comment by Tomino2112** [comment]
@sebastian, see my pull request for my suggestion how to implement both checked and unchecked. Sorry dont have time to write tests

**Comment by sebastianha** [comment]
What is the advantage of your version over my in the "checked-unchecked" branch?

**Comment by Tomino2112** [comment]
@sebastianha 

* It is cleaner
* It uses only one watch in ng-class
* Its more easily extendable

**Comment by sebastianha** [comment]
I think I found a better, universal solution, now ng-class just works as expected:
https://github.com/sebastianha/angular-bootstrap-checkbox/tree/ng-class

**Comment by Tomino2112** [comment]
Great! I didnt have time to test it yet, but just looking at it seems right.

**Comment by sebastianha** [comment]
Perfekt, as soon you had time to test it, I will merge it with the main branch and release a new version, let me know!

**Comment by Tomino2112** [comment]
@sebastianha  Sorry, didnt have time to do this earlier, Everything tested and it works well. Thank you

**Comment by sebastianha** [comment]
Thanks, I will merge it soon and release a new version!

**Comment by sebastianha** [comment]
Done, just released 0.4.0

**Pull request closed without merging**
